services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwe123!@#
      MYSQL_DATABASE: chatify_db
      MYSQL_USER: seungSoft
      MYSQL_PASSWORD: qwe123!@#
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h","127.0.0.1","-pqwe123!@#"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    container_name: chatify-app
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/chatify_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: seungSoft
      SPRING_DATASOURCE_PASSWORD: qwe123!@#
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    volumes:
      # 내 컴퓨터의 빌드 결과물을 컨테이너의 해당 경로와 동기화
      - ./build/classes/java/main:/app/classes
      - ./build/resources/main:/app/resources