spring:
  application:
    name: chatify
  datasource:
    url: jdbc:mysql://mysql:3306/chatify_db
    username : seungSoft
    password : qwe123!@#
    driver-class-name : com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto : update
    show-sql : true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret-key: ${JWT_SECRET_KEY} # ?? ?? ??: ? ?? ??? ?? ???? ? ???.
  access-token-expiration-ms: 1800000 # 30? (??? ??)
  refresh-token-expiration-ms: 604800000 # 7? (??? ??)



